(ql:quickload '(:str :binding-arrows :hu.dwim.defclass-star :parseq :lparallel :alexandria))
(defpackage :advent (:use :cl :binding-arrows :hu.dwim.defclass-star))
(in-package :advent)
;;(declaim (optimize (speed 3) (safety 0) (debug 0) (compilation-speed 0) (space 0)))

(defclass* device () (name (connections (list))))
(defun get-or-create (device devices)
  (or (gethash device devices) (setf (gethash device devices) (make-instance 'device :name device))))

(defun walk (device target &optional (memo (serapeum:dict)))
  (if (gethash device memo) (gethash device memo)
      (loop with valid = 0
            for connection in (connections-of device)
            for name = (name-of connection)
            if (string= target name)
              do (return 1)
            do (incf valid (walk connection target memo))
            finally (setf (gethash device memo) valid)
                    (return valid))))

(defun parse (input)
  (loop with out = (serapeum:dict)
        for line in (str:lines input)
        for parts = (str:split " " (str:trim line))
        for source = (get-or-create (str:substring 0 -1 (first parts)) out)
        do (loop for part in (rest parts)
                 for dest = (get-or-create part out)
                 do (push dest (connections-of source)))
        finally (return out)))

(defun part-1 (input) (walk (gethash "you" (parse input)) "out"))
(frog:report (part-1 (frog:get-advent-of-code-input 2025 11 :input-suffix "test")))
(frog:report (part-1 (frog:get-advent-of-code-input 2025 11)))

(defun part-2 (input)
  (let ((parsed (parse input)))
    (* (walk (gethash "svr" parsed) "fft")
       (walk (gethash "fft" parsed) "dac")
       (walk (gethash "dac" parsed) "out"))))
(frog:report (part-2 (frog:get-advent-of-code-input 2025 11 :input-suffix "test2")))
(frog:report (part-2 (frog:get-advent-of-code-input 2025 11)))
